Create Definition Type for different types
mukut1994/MK94.CodeGenerator pull request #19
Opened 2024-03-13 17:17 UTC by mithileshz

2024-03-13 19:11 UTC, mukut1994 requested changes

2024-03-13 19:11 UTC, mukut1994 commented on MK94.CodeGenerator/Intermediate/CSharp/Generator.cs
> +            public IntermediateTypeDefinition Type(string name, MemberFlags flags, DefinitionType definitionType)
DefintionType = class as default and overridden by `With` methods please.  

```C#
.Namespace("space")
  .Type("Type")
    .WithTypeAsRecord()
```

Same for the other changes

2024-03-14 10:16 UTC, mithileshz commented on MK94.CodeGenerator/Intermediate/CSharp/Generator.cs
> +            public IntermediateTypeDefinition Type(string name, MemberFlags flags, DefinitionType definitionType)
Fixed

2024-03-17 00:55 UTC, mukut1994 requested changes

2024-03-17 00:55 UTC, mukut1994 commented on MK94.CodeGenerator/Intermediate/CSharp/Generator.cs
> +            public IntermediateTypeDefinition WithTypeAsRecord()
Same issue as this [comment](https://github.com/mukut1994/MK94.CodeGenerator/pull/21/files#r1527386563).  
Refactor to use xor ops instead please.

2024-03-17 16:08 UTC, closed without merging